# Generated by Django 5.2.14 on 2026-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes_clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vente",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Adresse de livraison"
            ),
        ),
    ]
