# Generated by Django 5.2.14 on 2026-06-28 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventes_clients", "0002_alter_vente_delivery_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessioncaisse",
            options={
                "ordering": ["-opening_date"],
                "verbose_name": "Session de caisse",
                "verbose_name_plural": "Sessions de caisse",
            },
        ),
        migrations.RemoveField(
            model_name="paiement",
            name="sale",
        ),
        migrations.AddField(
            model_name="paiement",
            name="facture",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="ventes_clients.facture",
                verbose_name="Facture",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="facture",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyée"),
                    ("paid", "Payée"),
                    ("overdue", "En retard"),
                    ("cancelled", "Annulée"),
                    ("partial", "Partiellement payée"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant"
            ),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(
                fields=["facture", "payment_date"],
                name="ventes_clie_facture_fc88d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(fields=["method"], name="ventes_clie_method_cab22f_idx"),
        ),
    ]
