# Generated by Django 5.2.14 on 2026-06-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ventes_clients",
            "0003_alter_sessioncaisse_options_remove_paiement_sale_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="paiement",
            name="ventes_clie_facture_fc88d8_idx",
        ),
        migrations.RemoveIndex(
            model_name="paiement",
            name="ventes_clie_method_cab22f_idx",
        ),
        migrations.AddField(
            model_name="paiement",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="qrcodes/payments/",
                verbose_name="QR Code",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="qr_code_data",
            field=models.TextField(blank=True, verbose_name="Données QR Code"),
        ),
    ]
