# Generated by Django 5.2.14 on 2026-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'expiration"
            ),
        ),
    ]
